# Capítulo 3 > Continuando a aplicação > Conhecendo o docker > Usando o docker-compose
version: "3.7"

services:
    app:
        build: .
        container_name: rentx
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app